version: 0.2

env:
  variables:
    TF_INPUT: "false"
    REPO_PATH: "projects/wbd/sandbox/us-east-1/stack-network"
    REGION: "us-east-1"

phases:
  install:
    commands:
      # install terraform inside the CodeBuild container
      - curl -sSLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - terraform -version
      - yum install -y jq
  pre_build:
    commands:
      # set AWS region and show which account the creds belong to
      - export AWS_DEFAULT_REGION="$REGION"
      - echo "Caller identity (should be Destination account):"
      - aws sts get-caller-identity
      # move into the Terraform root for this stack
      - cd "$CODEBUILD_SRC_DIR/$REPO_PATH"
  build:
    commands:
      - terraform init -upgrade
      - terraform validate
      - terraform plan -out=tfplan.bin
      - terraform apply -auto-approve tfplan.bin

artifacts:
  files:
    - $REPO_PATH/tfplan.bin
